name: Build README
on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 0
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.1.0
      with:
        description: |
          A collection of issues, fixes and wonders I have noted during my professional
          career. My goal is to help myself and others by writing these publicly. Here's
          to google, hopefully they allow these TILs to help someone on their research.
          
          I am professional Automation Engineer working on both industrial and maritime
          sectors on Europe. Besides my work on automation systems like ABBs 800xA,
          Siemens Simatic and Codesys, I have done some personal projects on PC programming
          languages like Python3, Rust and C (for Teensy-platform).
          
          As a side-rant the industrial and maritime automation systems should really
          look into general programming workflows, and maybe learn a thing or two.
        footer: |
          Thanks cflynn07 (and Simon Wilson) for this github action. Please check out https://github.com/cflynn07/github-action-til-autoformat-readme.
        list_most_recent: 2 # optional, lists most recent TILS below description
